version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.8.1
    container_name: localstack
    ports:
      - "0.0.0.0:4566:4566"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoint.sh:/etc/localstack/init/ready.d/entrypoint.sh:ro
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "aws", "--endpoint-url=http://localhost:4566", "s3api", "list-buckets" ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-token-event-photo
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MONGO_URI=mongodb://mongodb:27017/myapp
    env_file:
      - .env
    depends_on:
      localstack:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
      - node_modules:/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  node_modules:
